OpenApi\InfoDeliveryBundle\Entity\Service:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '100'
        owner:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
